export const data = {
    nodes: [
        {
            id: 'customer',
            label: 'customer',
            type: 'entity'

        }, {
            id: 'customer_id',
            label: 'customer_id',
            type: 'property',
        }, {
            id: 'name',
            label: 'name',
            type: 'property',
        }, {
            id: 'address',
            label: 'address',
            type: 'property',
        }, {
            id: 'email',
            label: 'email',
            type: 'property',
        }, {
            id: 'order',
            label: 'order',
            type: 'entity',
        }, {
            id: 'order_id',
            label: 'order_id',
            type: 'property',
        }, {
            id: 'order_status',
            label: 'order_status',
            type: 'property',
        }, {
            id: 'total_price',
            label: 'total_price',
            type: 'property',
        }, {
            id: 'employee',
            label: 'employee',
            type: 'entity',
        }, {
            id: 'employee_id',
            label: 'employee_id',
            type: 'property',
        }, {
            id: 'title',
            label: 'title',
            type: 'property',
        }],
    edges: [{
        id: 'c_id',
        source: 'customer',
        target: 'customer_id'
    }, {
        id: 'c_name',
        source: 'customer',
        target: 'name'
    }, {
        id: 'c_address',
        source: 'customer',
        target: 'address'
    }, {
        id: 'c_email',
        source: 'customer',
        target: 'email'
    }, {
        id: 'o_id',
        source: 'order',
        target: 'order_id'

    }, {
        id: 'o_price',
        source: 'order',
        target: 'total_price'
    }, {
        id: 'o_status',
        source: 'order',
        target: 'order_status'
    }, {
        id: 'c_o',
        source: 'customer',
        target: 'order',
        relation: 'places',
        sourceEntity: '1',
        targetEntity: 'N',
        type: 'relation'
    }, {
        id: 'o_e',
        source: 'employee',
        target: 'order',
        relation: 'finalize',
        sourceEntity: '1',
        targetEntity: 'N',
        type: 'relation'
    }, {
        id: 'e_id',
        source: 'employee',
        target: 'employee_id'
    }, {
        id: 'e_title',
        source: 'employee',
        target: 'title'
    }]
};
